<a href="https://colab.research.google.com/github/Sunil032003/deep-learning-projects/blob/main/Deep_learninng1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input,Dropout

In [ ]:
df=pd.read_csv('/content/student-mat.csv',sep=';')

In [ ]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
df['Pstatus'].value_counts()

Pstatus
T    354
A     41
Name: count, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [ ]:
le=OneHotEncoder()

In [ ]:
catergorical=df.select_dtypes(include='object').columns

In [ ]:
print(catergorical)

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [ ]:
df=pd.get_dummies(df,columns=catergorical,drop_first=True)

In [ ]:
# Convert boolean columns (from one-hot encoding) to integers (0 or 1)
for col in df.select_dtypes(include='bool').columns:
    df[col] = df[col].astype(int)

print("DataFrame after converting boolean columns to int:")
display(df.head())

DataFrame after converting boolean columns to int:

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,1,0,0,0,1,1,0,0
1,17,1,1,1,2,0,5,3,3,1,...,0,0,0,1,0,0,0,1,1,0
2,15,1,1,1,2,3,4,3,2,2,...,1,0,1,0,1,0,1,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,1,0,0,1,1,1,1,1,1,1
4,16,3,3,1,2,0,4,3,2,1,...,0,0,0,1,1,0,1,1,0,0

In [ ]:
df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,True,False,True,False,False,False,True,True,False,False
1,17,1,1,1,2,0,5,3,3,1,...,False,False,False,True,False,False,False,True,True,False
2,15,1,1,1,2,3,4,3,2,2,...,True,False,True,False,True,False,True,True,True,False
3,15,4,2,1,3,0,3,2,2,1,...,True,False,False,True,True,True,True,True,True,True
4,16,3,3,1,2,0,4,3,2,1,...,False,False,False,True,True,False,True,True,False,False

In [ ]:
x=df.drop('G3',axis=1)
y=df['G3']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

(316, 41)

In [ ]:
model=Sequential([
Input(shape=(41,)),
Dense(128,activation='relu'),
Dense(64,activation='relu'),
Dense(32,activation='relu'),
Dense(1,activation='relu')])

In [ ]:
model.compile(optimizer='adam',loss='mse',metrics=['r2_score'])

In [ ]:
model.fit(x_train,y_train,epochs=500,batch_size=32,validation_data=(x_test,y_test))

Epoch 1/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 117.1486 - r2_score: -4.5773 - val_loss: 105.7891 - val_r2_score: -4.1592
Epoch 2/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 83.6757 - r2_score: -2.9837 - val_loss: 65.5294 - val_r2_score: -2.1958
Epoch 3/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 50.4756 - r2_score: -1.4031 - val_loss: 26.0005 - val_r2_score: -0.2680
Epoch 4/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.1057 - r2_score: -0.1476 - val_loss: 11.1924 - val_r2_score: 0.4542
Epoch 5/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 21.8284 - r2_score: -0.0392 - val_loss: 8.7351 - val_r2_score: 0.5740
Epoch 6/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 16.1611 - r2_score: 0.2306 - val_loss: 8.6062 - val_r2_score: 0.5803
Epoch 7/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 14.6965 - r2_score: 0.3003 - val_loss: 7.7367 - val_r2_score: 0.6227
Epoch 8/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 11.0866 - r2_score: 0.4722 - val_loss: 6.9893 - val_r2_score: 0.6591
Epoch 9/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 10.5176 - r2_score: 0.4993 - val_loss: 6.8165 - val_r2_score: 0.6676
Epoch 10/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 10.6895 - r2_score: 0.4911 - val_loss: 6.8895 - val_r2_score: 0.6640
Epoch 11/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 11.4856 - r2_score: 0.4532 - val_loss: 7.5373 - val_r2_score: 0.6324
Epoch 12/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 10.9247 - r2_score: 0.4799 - val_loss: 6.6547 - val_r2_score: 0.6755
Epoch 13/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.1902 - r2_score: 0.5625 - val_loss: 6.4296 - val_r2_score: 0.6864
Epoch 14/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 9.4098 - r2_score: 0.5520 - val_loss: 6.5551 - val_r2_score: 0.6803
Epoch 15/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 9.4766 - r2_score: 0.5488 - val_loss: 6.5967 - val_r2_score: 0.6783
Epoch 16/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 9.7637 - r2_score: 0.5352 - val_loss: 6.6360 - val_r2_score: 0.6764
Epoch 17/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 8.4987 - r2_score: 0.5954 - val_loss: 6.9581 - val_r2_score: 0.6607
Epoch 18/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.3596 - r2_score: 0.6020 - val_loss: 6.6639 - val_r2_score: 0.6750
Epoch 19/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.8343 - r2_score: 0.6270 - val_loss: 6.6572 - val_r2_score: 0.6753
Epoch 20/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.4577 - r2_score: 0.5973 - val_loss: 7.0993 - val_r2_score: 0.6538
Epoch 21/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.5262 - r2_score: 0.6417 - val_loss: 7.2873 - val_r2_score: 0.6446
Epoch 22/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.4361 - r2_score: 0.5984 - val_loss: 6.5531 - val_r2_score: 0.6804
Epoch 23/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.4068 - r2_score: 0.6474 - val_loss: 6.5211 - val_r2_score: 0.6820
Epoch 24/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 7.7236 - r2_score: 0.6323 - val_loss: 6.8279 - val_r2_score: 0.6670
Epoch 25/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1991 - r2_score: 0.6573 - val_loss: 6.2539 - val_r2_score: 0.6950
Epoch 26/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.6956 - r2_score: 0.6812 - val_loss: 6.5112 - val_r2_score: 0.6825
Epoch 27/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7.1354 - r2_score: 0.6603 - val_loss: 6.6975 - val_r2_score: 0.6734
Epoch 28/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 7.2788 - r2_score: 0.6535 - val_loss: 6.9666 - val_r2_score: 0.6602
Epoch 29/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.8022 - r2_score: 0.6762 - val_loss: 7.1293 - val_r2_score: 0.6523
Epoch 30/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.1779 - r2_score: 0.7059 - val_loss: 6.8255 - val_r2_score: 0.6671
Epoch 31/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 6.0399 - r2_score: 0.7124 - val_loss: 6.6005 - val_r2_score: 0.6781
Epoch 32/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.7401 - r2_score: 0.7267 - val_loss: 6.5553 - val_r2_score: 0.6803
Epoch 33/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 5.8699 - r2_score: 0.7205 - val_loss: 7.6409 - val_r2_score: 0.6274
Epoch 34/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 6.2658 - r2_score: 0.7017 - val_loss: 6.7707 - val_r2_score: 0.6698
Epoch 35/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 6.1112 - r2_score: 0.7091 - val_loss: 7.2305 - val_r2_score: 0.6474
Epoch 36/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.3964 - r2_score: 0.7431 - val_loss: 6.8565 - val_r2_score: 0.6656
Epoch 37/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 5.7316 - r2_score: 0.7271 - val_loss: 6.8794 - val_r2_score: 0.6645
Epoch 38/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 6.4056 - r2_score: 0.6950 - val_loss: 6.6320 - val_r2_score: 0.6766
Epoch 39/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 5.5060 - r2_score: 0.7379 - val_loss: 7.0175 - val_r2_score: 0.6578
Epoch 40/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 5.4459 - r2_score: 0.7407 - val_loss: 8.0857 - val_r2_score: 0.6057
Epoch 41/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 4.4661 - r2_score: 0.7874 - val_loss: 7.0107 - val_r2_score: 0.6581
Epoch 42/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 5.5517 - r2_score: 0.7357 - val_loss: 6.9432 - val_r2_score: 0.6614
Epoch 43/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 5.5125 - r2_score: 0.7376 - val_loss: 6.7900 - val_r2_score: 0.6689
Epoch 44/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 5.3249 - r2_score: 0.7465 - val_loss: 7.0364 - val_r2_score: 0.6568
Epoch 45/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.6475 - r2_score: 0.7311 - val_loss: 6.8706 - val_r2_score: 0.6649
Epoch 46/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 5.4574 - r2_score: 0.7402 - val_loss: 7.1596 - val_r2_score: 0.6508
Epoch 47/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.6850 - r2_score: 0.7293 - val_loss: 7.0338 - val_r2_score: 0.6570
Epoch 48/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.1806 - r2_score: 0.8010 - val_loss: 7.0225 - val_r2_score: 0.6575
Epoch 49/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 4.7544 - r2_score: 0.7736 - val_loss: 7.4146 - val_r2_score: 0.6384
Epoch 50/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 5.1457 - r2_score: 0.7550 - val_loss: 7.6834 - val_r2_score: 0.6253
Epoch 51/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.6351 - r2_score: 0.7793 - val_loss: 7.4760 - val_r2_score: 0.6354
Epoch 52/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.7916 - r2_score: 0.7719 - val_loss: 7.6459 - val_r2_score: 0.6271
Epoch 53/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.2577 - r2_score: 0.7973 - val_loss: 7.1282 - val_r2_score: 0.6524
Epoch 54/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.5271 - r2_score: 0.7845 - val_loss: 7.1338 - val_r2_score: 0.6521
Epoch 55/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3745 - r2_score: 0.7917 - val_loss: 7.1191 - val_r2_score: 0.6528
Epoch 56/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.5895 - r2_score: 0.7815 - val_loss: 7.3832 - val_r2_score: 0.6399
Epoch 57/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 5.1280 - r2_score: 0.7559 - val_loss: 6.9219 - val_r2_score: 0.6624
Epoch 58/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.3164 - r2_score: 0.7945 - val_loss: 6.9152 - val_r2_score: 0.6628
Epoch 59/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.8790 - r2_score: 0.8153 - val_loss: 7.4191 - val_r2_score: 0.6382
Epoch 60/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2007 - r2_score: 0.8000 - val_loss: 7.5462 - val_r2_score: 0.6320
Epoch 61/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.4123 - r2_score: 0.7899 - val_loss: 7.7159 - val_r2_score: 0.6237
Epoch 62/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.9085 - r2_score: 0.7663 - val_loss: 7.7342 - val_r2_score: 0.6228
Epoch 63/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1348 - r2_score: 0.8031 - val_loss: 7.4337 - val_r2_score: 0.6375
Epoch 64/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.5698 - r2_score: 0.7824 - val_loss: 7.2223 - val_r2_score: 0.6478
Epoch 65/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2690 - r2_score: 0.7968 - val_loss: 7.3240 - val_r2_score: 0.6428
Epoch 66/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.6402 - r2_score: 0.7791 - val_loss: 7.7365 - val_r2_score: 0.6227
Epoch 67/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 4.0173 - r2_score: 0.8087 - val_loss: 7.5874 - val_r2_score: 0.6300
Epoch 68/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6108 - r2_score: 0.8281 - val_loss: 7.4631 - val_r2_score: 0.6360
Epoch 69/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.0967 - r2_score: 0.8050 - val_loss: 8.1637 - val_r2_score: 0.6019
Epoch 70/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.8630 - r2_score: 0.8161 - val_loss: 7.9790 - val_r2_score: 0.6109
Epoch 71/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.0879 - r2_score: 0.8054 - val_loss: 7.9041 - val_r2_score: 0.6145
Epoch 72/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2262 - r2_score: 0.7988 - val_loss: 7.9790 - val_r2_score: 0.6109
Epoch 73/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.4815 - r2_score: 0.7866 - val_loss: 7.8876 - val_r2_score: 0.6153
Epoch 74/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.8587 - r2_score: 0.8163 - val_loss: 8.3155 - val_r2_score: 0.5945
Epoch 75/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.8833 - r2_score: 0.7675 - val_loss: 8.1176 - val_r2_score: 0.6041
Epoch 76/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.3817 - r2_score: 0.7914 - val_loss: 8.0447 - val_r2_score: 0.6077
Epoch 77/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4225 - r2_score: 0.8371 - val_loss: 7.6583 - val_r2_score: 0.6265
Epoch 78/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1549 - r2_score: 0.8022 - val_loss: 7.9714 - val_r2_score: 0.6112
Epoch 79/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.8653 - r2_score: 0.8160 - val_loss: 7.6926 - val_r2_score: 0.6248
Epoch 80/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.2410 - r2_score: 0.7981 - val_loss: 8.6211 - val_r2_score: 0.5796
Epoch 81/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.8108 - r2_score: 0.8186 - val_loss: 8.0498 - val_r2_score: 0.6074
Epoch 82/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.4272 - r2_score: 0.7892 - val_loss: 7.9584 - val_r2_score: 0.6119
Epoch 83/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.7768 - r2_score: 0.8202 - val_loss: 7.8322 - val_r2_score: 0.6180
Epoch 84/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.9636 - r2_score: 0.8113 - val_loss: 8.2715 - val_r2_score: 0.5966
Epoch 85/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.5104 - r2_score: 0.8329 - val_loss: 8.4103 - val_r2_score: 0.5898
Epoch 86/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.6257 - r2_score: 0.7798 - val_loss: 8.7691 - val_r2_score: 0.5723
Epoch 87/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.1439 - r2_score: 0.8027 - val_loss: 8.8937 - val_r2_score: 0.5663
Epoch 88/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.9243 - r2_score: 0.8132 - val_loss: 8.6703 - val_r2_score: 0.5772
Epoch 89/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4116 - r2_score: 0.8376 - val_loss: 8.8474 - val_r2_score: 0.5685
Epoch 90/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.7107 - r2_score: 0.8233 - val_loss: 8.5206 - val_r2_score: 0.5845
Epoch 91/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6958 - r2_score: 0.8240 - val_loss: 9.0500 - val_r2_score: 0.5586
Epoch 92/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 4.1465 - r2_score: 0.8026 - val_loss: 8.8265 - val_r2_score: 0.5695
Epoch 93/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4071 - r2_score: 0.8378 - val_loss: 8.4689 - val_r2_score: 0.5870
Epoch 94/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 4.2260 - r2_score: 0.7988 - val_loss: 8.4176 - val_r2_score: 0.5895
Epoch 95/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 3.5539 - r2_score: 0.8308 - val_loss: 8.4585 - val_r2_score: 0.5875
Epoch 96/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.6411 - r2_score: 0.8267 - val_loss: 8.6201 - val_r2_score: 0.5796
Epoch 97/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 4.0947 - r2_score: 0.8051 - val_loss: 8.3835 - val_r2_score: 0.5912
Epoch 98/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.5873 - r2_score: 0.8292 - val_loss: 8.3599 - val_r2_score: 0.5923
Epoch 99/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 4.3171 - r2_score: 0.7945 - val_loss: 8.6024 - val_r2_score: 0.5805
Epoch 100/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5638 - r2_score: 0.8303 - val_loss: 8.9982 - val_r2_score: 0.5612
Epoch 101/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5376 - r2_score: 0.8316 - val_loss: 8.8364 - val_r2_score: 0.5691
Epoch 102/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 4.4366 - r2_score: 0.7888 - val_loss: 8.7643 - val_r2_score: 0.5726
Epoch 103/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6902 - r2_score: 0.8243 - val_loss: 8.9158 - val_r2_score: 0.5652
Epoch 104/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5879 - r2_score: 0.8292 - val_loss: 8.3809 - val_r2_score: 0.5913
Epoch 105/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.9606 - r2_score: 0.8114 - val_loss: 8.5584 - val_r2_score: 0.5826
Epoch 106/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.2414 - r2_score: 0.8457 - val_loss: 8.5071 - val_r2_score: 0.5851
Epoch 107/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.8821 - r2_score: 0.8152 - val_loss: 8.7153 - val_r2_score: 0.5750
Epoch 108/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.7460 - r2_score: 0.8217 - val_loss: 9.1880 - val_r2_score: 0.5519
Epoch 109/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6123 - r2_score: 0.8280 - val_loss: 8.6885 - val_r2_score: 0.5763
Epoch 110/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3.4249 - r2_score: 0.8369 - val_loss: 8.8088 - val_r2_score: 0.5704
Epoch 111/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3.3023 - r2_score: 0.8428 - val_loss: 8.8223 - val_r2_score: 0.5698
Epoch 112/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 3.8874 - r2_score: 0.8149 - val_loss: 8.5925 - val_r2_score: 0.5810
Epoch 113/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3.7437 - r2_score: 0.8218 - val_loss: 8.6307 - val_r2_score: 0.5791
Epoch 114/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.1631 - r2_score: 0.8494 - val_loss: 8.4631 - val_r2_score: 0.5873
Epoch 115/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3.7162 - r2_score: 0.8231 - val_loss: 8.2893 - val_r2_score: 0.5957
Epoch 116/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 3.5485 - r2_score: 0.8311 - val_loss: 8.5913 - val_r2_score: 0.5810
Epoch 117/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 3.7474 - r2_score: 0.8216 - val_loss: 8.5862 - val_r2_score: 0.5813
Epoch 118/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 3.3862 - r2_score: 0.8388 - val_loss: 8.6977 - val_r2_score: 0.5758
Epoch 119/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 3.5607 - r2_score: 0.8305 - val_loss: 9.1745 - val_r2_score: 0.5526
Epoch 120/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 3.0131 - r2_score: 0.8565 - val_loss: 9.0089 - val_r2_score: 0.5606
Epoch 121/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 4.2144 - r2_score: 0.7994 - val_loss: 8.6824 - val_r2_score: 0.5766
Epoch 122/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.1748 - r2_score: 0.8489 - val_loss: 8.6453 - val_r2_score: 0.5784
Epoch 123/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.0541 - r2_score: 0.8070 - val_loss: 8.8889 - val_r2_score: 0.5665
Epoch 124/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 3.3773 - r2_score: 0.8392 - val_loss: 9.2989 - val_r2_score: 0.5465
Epoch 125/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3789 - r2_score: 0.8391 - val_loss: 8.8885 - val_r2_score: 0.5665
Epoch 126/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3894 - r2_score: 0.8386 - val_loss: 8.9202 - val_r2_score: 0.5650
Epoch 127/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.6923 - r2_score: 0.8242 - val_loss: 8.5553 - val_r2_score: 0.5828
Epoch 128/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5178 - r2_score: 0.8325 - val_loss: 8.3942 - val_r2_score: 0.5906
Epoch 129/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6622 - r2_score: 0.8256 - val_loss: 9.0763 - val_r2_score: 0.5574
Epoch 130/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6769 - r2_score: 0.8249 - val_loss: 8.4789 - val_r2_score: 0.5865
Epoch 131/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3045 - r2_score: 0.8427 - val_loss: 8.5423 - val_r2_score: 0.5834
Epoch 132/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5598 - r2_score: 0.8305 - val_loss: 8.7238 - val_r2_score: 0.5746
Epoch 133/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5483 - r2_score: 0.8311 - val_loss: 8.7978 - val_r2_score: 0.5709
Epoch 134/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8728 - r2_score: 0.8632 - val_loss: 8.4908 - val_r2_score: 0.5859
Epoch 135/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.4251 - r2_score: 0.8369 - val_loss: 8.3839 - val_r2_score: 0.5911
Epoch 136/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3160 - r2_score: 0.8421 - val_loss: 8.4465 - val_r2_score: 0.5881
Epoch 137/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3835 - r2_score: 0.8389 - val_loss: 8.6970 - val_r2_score: 0.5759
Epoch 138/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3780 - r2_score: 0.8392 - val_loss: 8.7703 - val_r2_score: 0.5723
Epoch 139/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4261 - r2_score: 0.8369 - val_loss: 8.5106 - val_r2_score: 0.5850
Epoch 140/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6027 - r2_score: 0.8285 - val_loss: 8.5341 - val_r2_score: 0.5838
Epoch 141/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5902 - r2_score: 0.8291 - val_loss: 8.6178 - val_r2_score: 0.5797
Epoch 142/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 3.7394 - r2_score: 0.8220 - val_loss: 8.4896 - val_r2_score: 0.5860
Epoch 143/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.6004 - r2_score: 0.8286 - val_loss: 8.4726 - val_r2_score: 0.5868
Epoch 144/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0885 - r2_score: 0.8530 - val_loss: 8.2042 - val_r2_score: 0.5999
Epoch 145/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.2682 - r2_score: 0.8444 - val_loss: 8.6398 - val_r2_score: 0.5787
Epoch 146/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.4901 - r2_score: 0.8338 - val_loss: 8.3911 - val_r2_score: 0.5908
Epoch 147/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.8165 - r2_score: 0.8659 - val_loss: 8.8748 - val_r2_score: 0.5672
Epoch 148/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.8689 - r2_score: 0.8634 - val_loss: 9.0173 - val_r2_score: 0.5602
Epoch 149/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.5515 - r2_score: 0.8785 - val_loss: 8.7366 - val_r2_score: 0.5739
Epoch 150/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.1916 - r2_score: 0.8480 - val_loss: 8.6609 - val_r2_score: 0.5776
Epoch 151/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.3119 - r2_score: 0.8423 - val_loss: 8.7627 - val_r2_score: 0.5727
Epoch 152/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.0455 - r2_score: 0.8550 - val_loss: 8.5292 - val_r2_score: 0.5840
Epoch 153/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.3677 - r2_score: 0.8397 - val_loss: 8.5916 - val_r2_score: 0.5810
Epoch 154/500
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 3.5904 - r2_score: 0.8291 - val_loss: 8.4751 - val_r2_score: 0.5867
Epoch 155/500

In [ ]:
predict=model.predict(x_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
print(r2_score(y_test,predict))

0.539239764213562